version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "09:00"
    groups:
        python-packages:
          patterns:
            - "*"
    target-branch: "main"
    commit-message:
      prefix: "pip prod"
      include: "scope"
    labels:
      - "🛠️ maintenance"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    target-branch: "main"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    labels:
      - "🛠️ maintenance"
